sudo: false
language: shell

addons:
  apt:
    packages:
      - ftp

script:
  - tools/get-raw-list.sh
  - tools/pac-generator-http.sh dnsmasq-china-list/accelerated-domains.china.raw.txt > http-temp.pac
  - tools/pac-generator-https.sh dnsmasq-china-list/accelerated-domains.china.raw.txt > https-temp.pac

deploy:
  provider: script
  script: tools/upload-pac.sh
  on:
    branch: master
    condition: '-n "$FTP_PASS"'
  skip_cleanup: true
