name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch: {}
  schedule:
    - cron: '30 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get -y install expect

      - name: Generate PAC
        run: |
          tools/get-raw-list.sh
          tools/pac-generator-http.sh dnsmasq-china-list/accelerated-domains.china.raw.txt > http-temp.pac
          tools/pac-generator-https.sh dnsmasq-china-list/accelerated-domains.china.raw.txt > https-temp.pac

      - name: Deploy
        run: tools/upload-pac.sh
        if: "github.ref == 'refs/heads/master' && env.FTP_PASS != null"
        env:
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
